# -*- coding: utf-8 -*-
"""plotly_assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z0hMLRvHixhbE8INQevC0vBfY_eG89F3
"""

import seaborn as sns
import plotly.express as px



"""Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
scatter plot for age and fare columns in the titanic dataset.
"""

df=sns.load_dataset("titanic")
scatter_plot=px.scatter(df, x="age",y="fare",title="scatter plot of age vs fare")
scatter_plot.show()



"""Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express."""

df1=sns.load_dataset("tips")
box_plot=px.box(df1,x="day",y="total_bill",title="box plot of day vs total_bill")
box_plot.show()



"""Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
column with the color parameter.
"""

histogram=px.histogram(df1,x="sex",y="total_bill",color="day",pattern_shape="smoker",title="Histogram of total bill amounts by sex",
                       labels={"sex":"Sex","total_bill":"TOTAL BILL"},
                       category_orders={"sex":["Male","Female"]})

histogram.show()



"""Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for
the color parameter.
Note: Use "sepal_length", "sepal_width", "petal_length", "petal_width" columns only with the
dimensions parameter.
"""

df2=sns.load_dataset("iris")

matrix_plot=px.scatter_matrix(df2,
                              dimensions=["sepal_length", "sepal_width" , "petal_length" , "petal_width"],
                              color="species",
                              title="Scatter matrix plot of iris dataset")
matrix_plot.update_traces(diagonal_visible=True)
matrix_plot.show()

"""Q5. What is Distplot? Using Plotly express, plot a distplot.

distplot is a function provided by the Seaborn library, not Plotly Express. It is used to create a histogram along with a kernel density estimate (KDE) plot for a given dataset. However, Plotly Express offers a similar functionality using its hist function. Here's how you can create a histogram with a KDE plot using Plotly Express:
"""

df3=sns.load_dataset("tips")

hist_kde=px.histogram(df3,x="total_bill",marginal="rug",title="Histogram with KDE")

hist_kde.show()

